[package]
name = "goout-calendar"
version = "0.1.0"
authors = ["Matěj Laitl <matej@laitl.cz>"]
edition = "2018"

[dependencies]
html5ever = "*"
reqwest = "0.9"
rocket = "0.4.0"
scraper = "0.9"
serde_json = "1.0"
single = "1.0"
