steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/goout-calendar:$SHORT_SHA', '.']
  timeout: 1800s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/goout-calendar:$SHORT_SHA']
# Generate knativeservice.yaml with variables filled-in. nginx is an arbitrary
# well-known image that contains the needed envsubst command:
- name: 'nginx'
  args: ['sh', '-c', 'envsubst < knativeservice.envsubst.yaml > knativeservice.yaml']
  env:
  - 'IMAGE_TAG=$SHORT_SHA'
# Deploy to Google Cloud Run using Knative service definition:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'services', 'replace', 'knativeservice.yaml', '--platform=managed', '--region=us-east1']
images: ['gcr.io/$PROJECT_ID/goout-calendar:$SHORT_SHA']
timeout: 1920s
