steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/goout-calendar:$SHORT_SHA', '.']
  timeout: 900s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/goout-calendar:$SHORT_SHA']
images: ['gcr.io/$PROJECT_ID/goout-calendar:$SHORT_SHA']
timeout: 1000s
