apiVersion: v1
kind: Service
metadata:
  name: goout-calendar
  labels:
    app: goout-calendar
  annotations:
    # https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: goout-calendar
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: goout-calendar
  labels:
    app: goout-calendar
spec:
  backend:
    serviceName: goout-calendar
    servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goout-calendar
  labels:
    app: goout-calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goout-calendar
  template:
    metadata:
      labels:
        app: goout-calendar
    spec:
      containers:
      - name: goout-calendar
        image: gcr.io/strohel-goout-calendar/goout-calendar:$IMAGE_TAG
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 50Mi
          requests:
            memory: 20Mi
            cpu: 0.05
